# Generated by Django 4.2.1 on 2023-05-20 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_rename_user_ouser"),
    ]

    operations = [
        migrations.RenameModel(old_name="OUser", new_name="SignedupUser",),
    ]
