# Generated by Django 4.2.1 on 2023-05-18 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("date_of_birth", models.DateField(default=datetime.date(2023, 5, 18))),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=120,
                    ),
                ),
                (
                    "school_grade",
                    models.CharField(
                        choices=[
                            ("", "select"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                        ],
                        max_length=120,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contact_number", models.CharField(max_length=10)),
                (
                    "item",
                    models.CharField(
                        choices=[
                            ("", "select 1 item"),
                            ("1", "Painting: Crayons"),
                            ("2", "Pencil Drawing"),
                            ("3", "Painting: Water Colour"),
                            ("4", "Cartoon"),
                            ("5", "Elocution Malayalam"),
                            ("6", "Elocution English"),
                            ("7", "Elocution Hindi"),
                            ("8", "Recitation Malayalam"),
                            ("9", "Recitation English"),
                            ("10", "Recitation Hindi"),
                            ("11", "Essay Writing English"),
                            ("12", "Essay Writing Malayalam"),
                            ("13", "Light Music"),
                            ("14", "Classical Music"),
                            ("15", "Mappilapattu"),
                            ("16", "Monoact"),
                            ("17", "Mimicry"),
                            ("18", "Folk Dance"),
                            ("19", "Bharathanatyam"),
                            ("20", "Mohiniyattam"),
                            ("21", "Guitar"),
                            ("22", "Key Board-Western"),
                            ("23", "Tabala-Eastern"),
                            ("24", "Group Song"),
                            ("25", "Group Dance"),
                        ],
                        max_length=120,
                    ),
                ),
            ],
        ),
    ]
