# Generated by Django 4.2.1 on 2023-05-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registered", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="gender",
            field=models.CharField(
                choices=[
                    ("", "Select Gender"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                ],
                max_length=120,
            ),
        ),
    ]
