# Generated by Django 4.2.1 on 2023-05-19 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registered", "0002_alter_form_email_alter_form_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="date_of_birth",
            field=models.DateField(default=datetime.date(2023, 5, 19)),
        ),
        migrations.AlterField(
            model_name="form", name="email", field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="form",
            name="gender",
            field=models.CharField(
                choices=[
                    ("", "Select Gender"),
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                ],
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="item",
            field=models.CharField(
                choices=[
                    ("", "select 1 item"),
                    ("Painting: Crayons", "Painting: Crayons"),
                    ("Pencil Drawing", "Pencil Drawing"),
                    ("Painting: Water Colour", "Painting: Water Colour"),
                    ("Cartoon", "Cartoon"),
                    ("Elocution Malayalam", "Elocution Malayalam"),
                    ("Elocution English", "Elocution English"),
                    ("Elocution Hindi", "Elocution Hindi"),
                    ("Recitation Malayalam", "Recitation Malayalam"),
                    ("Recitation English", "Recitation English"),
                    ("Recitation Hindi", "Recitation Hindi"),
                    ("Essay Writing English", "Essay Writing English"),
                    ("Essay Writing Malayalam", "Essay Writing Malayalam"),
                    ("Light Music", "Light Music"),
                    ("Classical Music", "Classical Music"),
                    ("Mappilapattu", "Mappilapattu"),
                    ("Monoact", "Monoact"),
                    ("Mimicry", "Mimicry"),
                    ("Folk Dance", "Folk Dance"),
                    ("Bharathanatyam", "Bharathanatyam"),
                    ("Mohiniyattam", "Mohiniyattam"),
                    ("Guitar", "Guitar"),
                    ("Key Board-Western", "Key Board-Western"),
                    ("Tabala-Eastern", "Tabala-Eastern"),
                    ("Group Song", "Group Song"),
                    ("Group Dance", "Group Dance"),
                ],
                max_length=120,
            ),
        ),
    ]
